export const HOBBIES = [
  { name: '3D printing' },
  { name: 'Acrobatics' },
  { name: 'Acting' },
  { name: 'Action figures' },
  { name: 'Air sports' },
  { name: 'Aircraft spotting' },
  { name: 'Airsoft' },
  { name: 'Amateur astronomy' },
  { name: 'Amateur radio' },
  { name: 'American football' },
  { name: 'Animal fancy' },
  { name: 'Animation' },
  { name: 'Antiquing' },
  { name: 'Antiquities' },
  { name: 'Aquascaping' },
  { name: 'Archery' },
  { name: 'Art collecting' },
  { name: 'Association football' },
  { name: 'Astrology' },
  { name: 'Astronomy' },
  { name: 'Audiophile' },
  { name: 'Australian rules football' },
  { name: 'Auto audiophilia' },
  { name: 'Auto racing' },
  { name: 'Axe throwing' },
  { name: 'Badminton' },
  { name: 'Baking' },
  { name: 'Base jumping' },
  { name: 'Baseball' },
  { name: 'Basketball' },
  { name: 'Baton twirling' },
  { name: 'Beach volleyball' },
  { name: 'Beatboxing' },
  { name: 'Beekeeping' },
  { name: 'Billiards' },
  { name: 'Bird watching' },
  { name: 'Blacksmithing' },
  { name: 'BMX' },
  { name: 'Board/tabletop games' },
  { name: 'Bodybuilding' },
  { name: 'Book collecting' },
  { name: 'Book restoration' },
  { name: 'Bowling' },
  { name: 'Boxing' },
  { name: 'Brazilian jiu-jitsu' },
  { name: 'Breakdancing' },
  { name: 'Bridge' },
  { name: 'Bus spotting' },
  { name: 'Butterfly watching' },
  { name: 'Cabaret' },
  { name: 'Calligraphy' },
  { name: 'Camping' },
  { name: 'Candle making' },
  { name: 'Canoeing' },
  { name: 'Canyoning' },
  { name: 'Cartophily (card collecting)' },
  { name: 'Cheerleading' },
  { name: 'Chess' },
  { name: 'Climbing' },
  { name: 'Coffee roasting' },
  { name: 'Coin collecting' },
  { name: 'Collecting' },
  { name: 'Color guard' },
  { name: 'Coloring' },
  { name: 'Comic book collecting' },
  { name: 'Computer programming' },
  { name: 'Cooking' },
  { name: 'Cosplaying' },
  { name: 'Couponing' },
  { name: 'Creative writing' },
  { name: 'Cricket' },
  { name: 'Crocheting' },
  { name: 'Cross-stitch' },
  { name: 'Crossword puzzles' },
  { name: 'Cryptography' },
  { name: 'Curling' },
  { name: 'Cycling' },
  { name: 'Dancing' },
  { name: 'Darts' },
  { name: 'Debate' },
  { name: 'Deltiology (postcard collecting)' },
  { name: 'Die-cast toy' },
  { name: 'Digital arts' },
  { name: 'Disc golf' },
  { name: 'Do it yourself' },
  { name: 'Dog sports' },
  { name: 'Dolls' },
  { name: 'Dowsing' },
  { name: 'Drama' },
  { name: 'Drawing' },
  { name: 'Driving' },
  { name: 'Eating' },
  { name: 'Electronics' },
  { name: 'Element collecting' },
  { name: 'Embroidery' },
  { name: 'Equestrianism' },
  { name: 'Esports' },
  { name: 'Exhibition drill' },
  { name: 'Fantasy sports' },
  { name: 'Fashion' },
  { name: 'Fencing' },
  { name: 'Field hockey' },
  { name: 'Figure skating' },
  { name: 'Fishing' },
  { name: 'Fishkeeping' },
  { name: 'Flag football' },
  { name: 'Flower arranging' },
  { name: 'Flower collecting and pressing' },
  { name: 'Flying' },
  { name: 'Flying disc' },
  { name: 'Footbag' },
  { name: 'Foraging' },
  { name: 'Foreign language learning' },
  { name: 'Fossil hunting' },
  { name: 'Freestyle football' },
  { name: 'Fusilately (phonecard collecting)' },
  { name: 'Gaming (tabletop games and role-playing games)' },
  { name: 'Gardening' },
  { name: 'Genealogy' },
  { name: 'Geocaching' },
  { name: 'Ghost hunting' },
  { name: 'Glassblowing' },
  { name: 'Go' },
  { name: 'Gold prospecting' },
  { name: 'Golfing' },
  { name: 'Gongoozling' },
  { name: 'Graffiti' },
  { name: 'Graphic design' },
  { name: 'Gunsmithing' },
  { name: 'Gymnastics' },
  { name: 'Handball' },
  { name: 'Herp keeping' },
  { name: 'Herping' },
  { name: 'High-power rocketry' },
  { name: 'Hiking/backpacking' },
  { name: 'Homebrewing' },
  { name: 'Hooping' },
  { name: 'Horseback riding' },
  { name: 'Hunting' },
  { name: 'Hydroponics' },
  { name: 'Ice hockey' },
  { name: 'Ice skating' },
  { name: 'Inline skating' },
  { name: 'Insect collecting' },
  { name: 'Jewelry making' },
  { name: 'Jigsaw puzzles' },
  { name: 'Jogging' },
  { name: 'Judo' },
  { name: 'Juggling' },
  { name: 'Jukskei' },
  { name: 'Kabaddi' },
  { name: 'Karate' },
  { name: 'Kart racing' },
  { name: 'Kayaking' },
  { name: 'Kite flying' },
  { name: 'Kitesurfing' },
  { name: 'Knife collecting' },
  { name: 'Knife making' },
  { name: 'Knife throwing' },
  { name: 'Knitting' },
  { name: 'Kombucha brewing' },
  { name: 'Lace making' },
  { name: 'Lacrosse' },
  { name: 'Lapidary' },
  { name: 'LARPing' },
  { name: 'Laser tag' },
  { name: 'Learning' },
  { name: 'Leather crafting' },
  { name: 'Lego building' },
  { name: 'Letterboxing' },
  { name: 'Listening to music' },
  { name: 'Lock picking' },
  { name: 'Longboarding' },
  { name: 'Lotology (lottery ticket collecting)' },
  { name: 'Machining' },
  { name: 'Macrame' },
  { name: 'Magic' },
  { name: 'Magnet fishing' },
  { name: 'Mahjong' },
  { name: 'Marbles' },
  { name: 'Marching band' },
  { name: 'Martial arts' },
  { name: 'Meditation' },
  { name: 'Meme Fact Checking' },
  { name: 'Metal detecting' },
  { name: 'Metalworking' },
  { name: 'Meteorology' },
  { name: 'Microscopy' },
  { name: 'Mineral collecting' },
  { name: 'Model aircraft' },
  { name: 'Model building' },
  { name: 'Model engineering' },
  { name: 'Motor sports' },
  { name: 'Mountain biking' },
  { name: 'Mountaineering' },
  { name: 'Movie and movie memorabilia collecting' },
  { name: 'Mushroom hunting/mycology' },
  { name: 'Needlepoint' },
  { name: 'Netball' },
  { name: 'Nordic skating' },
  { name: 'Orienteering' },
  { name: 'Origami' },
  { name: 'Paintball' },
  { name: 'Painting' },
  { name: 'Parkour' },
  { name: 'Perfume' },
  { name: 'Philately' },
  { name: 'Phillumeny' },
  { name: 'Photography' },
  { name: 'Playing musical instruments' },
  { name: 'Poi' },
  { name: 'Poker' },
  { name: 'Polo' },
  { name: 'Pottery' },
  { name: 'Powerlifting' },
  { name: 'Puzzles' },
  { name: 'Quilling' },
  { name: 'Quilting' },
  { name: 'Racquetball' },
  { name: 'Radio-controlled car racing' },
  { name: 'Rafting' },
  { name: 'Rail transport modelling' },
  { name: 'Rappelling' },
  { name: 'Reading' },
  { name: 'Record collecting' },
  { name: 'Road biking' },
  { name: 'Robot combat' },
  { name: 'Rock balancing' },
  { name: 'Rock climbing' },
  { name: 'Roller derby' },
  { name: 'Roller skating' },
  { name: 'Rugby' },
  { name: 'Running' },
  { name: 'Sailing' },
  { name: 'Sand art' },
  { name: 'Satellite watching' },
  { name: 'Scouting' },
  { name: 'Scrapbooking' },
  { name: 'Scuba diving' },
  { name: 'Sculling or rowing' },
  { name: 'Sculpting' },
  { name: 'Sea glass collecting' },
  { name: 'Seashell collecting' },
  { name: 'Sewing' },
  { name: 'Shoes' },
  { name: 'Shogi' },
  { name: 'Shooting' },
  { name: 'Shopping' },
  { name: 'Shortwave listening' },
  { name: 'Singing' },
  { name: 'Skateboarding' },
  { name: 'Sketching' },
  { name: 'Skiing' },
  { name: 'Skimboarding' },
  { name: 'Skydiving' },
  { name: 'Slacklining' },
  { name: 'Slot car racing' },
  { name: 'Snowboarding' },
  { name: 'Soapmaking' },
  { name: 'Speed skating' },
  { name: 'Speedcubing' },
  { name: 'Sport stacking' },
  { name: 'Squash' },
  { name: 'Stamp collecting' },
  { name: 'Stand-up comedy' },
  { name: 'Stone collecting' },
  { name: 'Stone skipping' },
  { name: 'Sun bathing' },
  { name: 'Surfing' },
  { name: 'Swimming' },
  { name: 'Table football' },
  { name: 'Table tennis' },
  { name: 'Taekwondo' },
  { name: 'Tai chi' },
  { name: 'Taxidermy' },
  { name: 'Tea bag collecting' },
  { name: 'Tennis' },
  { name: 'Tennis polo' },
  { name: 'Tether car' },
  { name: 'Ticket collecting' },
  { name: 'Topiary' },
  { name: 'Tour skating' },
  { name: 'Trainspotting' },
  { name: 'Traveling' },
  { name: 'Triathlon' },
  { name: 'Ultimate frisbee' },
  { name: 'Urban exploration' },
  { name: 'Vacation' },
  { name: 'Vehicle restoration' },
  { name: 'Video editing' },
  { name: 'Video game collecting' },
  { name: 'Video game developing' },
  { name: 'Video gaming' },
  { name: 'Videophilia' },
  { name: 'Vintage cars' },
  { name: 'Volleyball' },
  { name: 'Walking' },
  { name: 'Watching movies' },
  { name: 'Watching television' },
  { name: 'Water polo' },
  { name: 'Water sports' },
  { name: 'Weightlifting' },
  { name: 'Whale watching' },
  { name: 'Whittling' },
  { name: 'Wood carving' },
  { name: 'Woodworking' },
  { name: 'Worldbuilding' },
  { name: 'Wrestling' },
  { name: 'Writing' },
  { name: 'Yo-yoing' },
  { name: 'Yoga' },
];
