export const INDUSTRY_INTERESTS = [
  { name: 'Agriculture, Forestry, Fishing and Hunting' },
  { name: 'Mining, Quarrying, and Oil and Gas Extraction' },
  { name: 'Utilities' },
  { name: 'Construction' },
  { name: 'Manufacturing' },
  { name: 'Wholesale Trade' },
  { name: 'Retail Trade' },
  { name: 'Transportation and Warehousing' },
  { name: 'Information' },
  { name: 'Finance and Insurance' },
  { name: 'Real Estate and Rental and Leasing' },
  { name: 'Professional, Scientific, and Technical Services' },
  { name: 'Management of Companies and Enterprises' },
  { name: 'Administrative and Support and Waste Management and Remediation Services' },
  { name: 'Educational Services' },
  { name: 'Health Care and Social Assistance' },
  { name: 'Arts, Entertainment, and Recreation' },
  { name: 'Accommodation and Food Services' },
  { name: 'Other Services (except Public Administration)' },
  { name: 'Public Administration' },
];
