export const SKILLS = [
  { name: 'Administration of Justice' },
  { name: 'Account Tools (SAP, Oracle, etc.)' },
  { name: 'Accounting' },
  { name: 'Actuarial Science' },
  { name: 'Administrative Support' },
  { name: 'Adobe Creative Suite (Photoshop, etc.)' },
  { name: 'Adobe Sparks' },
  { name: 'Advanced Bookkeeping' },
  { name: 'Advanced Lifesaving (ACLS)' },
  { name: 'Advertising' },
  { name: 'Aerospace Engineering' },
  { name: 'Agile Methodologies (Scrum)' },
  { name: 'Agribusiness' },
  { name: 'Agriculture Science' },
  { name: 'Algorithm Design' },
  { name: 'American Indian Studies' },
  { name: 'American Studies' },
  { name: 'Android Development' },
  { name: 'Angular and Node Apps' },
  { name: 'Animal Management' },
  { name: 'Anthropology' },
  { name: 'Applied Cognition and Neuroscience' },
  { name: 'Applied Psychology' },
  { name: 'Architectural Engineering' },
  { name: 'Architecture' },
  { name: 'Archives and Records Management' },
  { name: 'Art' },
  { name: 'Athletic Training' },
  { name: 'Audiology' },
  { name: 'Auditing' },
  { name: 'Authentication Systems' },
  { name: 'Automotive Maintenance' },
  { name: 'Aviation' },
  { name: 'Aviation Mechanics' },
  { name: 'Back-end Development' },
  { name: 'Behavioral Science' },
  { name: 'BI Tools & Apps' },
  { name: 'Biblical Studies' },
  { name: 'Bioethics' },
  { name: 'Bioinformatics' },
  { name: 'Biology' },
  { name: 'Biomedical Engineering' },
  { name: 'Biomedical Science' },
  { name: 'Biotechnology' },
  { name: 'Blackboard' },
  { name: 'Blog Creation' },
  { name: 'Boat Repair and Maintenance' },
  { name: 'Bookkeeping' },
  { name: 'Brainstorming' },
  { name: 'Branding' },
  { name: 'Budget Management' },
  { name: 'Budgeting' },
  { name: 'Buffer' },
  { name: 'Business & Data Analysis' },
  { name: 'Business Administration' },
  { name: 'Business Analytics' },
  { name: 'Business and Technology' },
  { name: 'Business Engineering' },
  { name: 'Business Informatics' },
  { name: 'Business Information Systems' },
  { name: 'Business Intelligence' },
  { name: 'Cabinet Design' },
  { name: 'Campaign Management' },
  { name: 'Canon Law' },
  { name: 'Canva' },
  { name: 'Carpentry' },
  { name: 'Catheterization' },
  { name: 'Chemical Engineering' },
  { name: 'Chemistry' },
  { name: 'Chemotherapy Administration' },
  { name: 'Child Advocacy' },
  { name: 'Child Development' },
  { name: 'Chiropractic' },
  { name: 'Christian Ministry' },
  { name: 'City Planning' },
  { name: 'Civil Engineering' },
  { name: 'Civil Justice / Law Enforcement' },
  { name: 'Clinical Epidemiology' },
  { name: 'Clinical Laboratory Science' },
  { name: 'Clinical Medical Assisting' },
  { name: 'Clinical Psychology' },
  { name: 'Clinical Science' },
  { name: 'Cloud and Distributed Computing' },
  { name: 'Cloud Apps (JSON, Rest, etc.)' },
  { name: 'Cloud Architecture' },
  { name: 'Cloud Computing' },
  { name: 'Cognitive Science' },
  { name: 'Commerce' },
  { name: 'Communication' },
  { name: 'Community Health' },
  { name: 'Computer Applications' },
  { name: 'Computer Electronics' },
  { name: 'Computer Engineering' },
  { name: 'Computer Game Design' },
  { name: 'Computer Information Science' },
  { name: 'Computer Information Systems' },
  { name: 'Computer Science' },
  { name: 'Computing Research' },
  { name: 'Conflict Management' },
  { name: 'Construction Engineering' },
  { name: 'Construction Management' },
  { name: 'Construction Technology' },
  { name: 'Content Management Systems (CMS)' },
  { name: 'Conversion Testing' },
  { name: 'Cooking and Baking' },
  { name: 'Copywriting' },
  { name: 'Corrections, Probation, and Parole' },
  { name: 'Cosmetology' },
  { name: 'Cost & Trend Analysis' },
  { name: 'Counseling' },
  { name: 'Creating PLNs' },
  { name: 'Creative Technologies' },
  { name: 'Creative Writing' },
  { name: 'Criminal Justice' },
  { name: 'Criminology' },
  { name: 'Cryptography' },
  { name: 'CSS' },
  { name: 'Culinary Arts' },
  { name: 'Cultural Intelligence' },
  { name: 'Customer Service' },
  { name: 'Cyber Security' },
  { name: 'Data Analysis' },
  { name: 'Data Engineering and Data Warehousing' },
  { name: 'Data Loss Prevention (DLP)' },
  { name: 'Data Mining' },
  { name: 'Database Management' },
  { name: 'Dental Surgery' },
  { name: 'Design' },
  { name: 'Development Administration' },
  { name: 'Development Framework' },
  { name: 'Diabetic Care' },
  { name: 'Diagnostic Radiography' },
  { name: 'Dialysis' },
  { name: 'Digital Advertising' },
  { name: 'Digital Communication' },
  { name: 'Digital Media' },
  { name: 'Digital Media Communications' },
  { name: 'Digital Photography' },
  { name: 'Digital Portfolio Creation' },
  { name: 'Digital Product Design Software (InVision, etc.)' },
  { name: 'Divinity' },
  { name: 'Early Childhood Education' },
  { name: 'Early Childhood Special Education' },
  { name: 'Economics' },
  { name: 'Education' },
  { name: 'Educational Technology' },
  { name: 'Electrical Engineering' },
  { name: 'Electronic Engineering' },
  { name: 'Elementary Education' },
  { name: 'Emergency Medical Services' },
  { name: 'Encryption Algorithms' },
  { name: 'Engineering Management' },
  { name: 'Engineering Physics' },
  { name: 'Engineering Science' },
  { name: 'Engineering Technology' },
  { name: 'English' },
  { name: 'English Literature' },
  { name: 'Enterprise' },
  { name: 'Environmental Cleanup' },
  { name: 'Environmental Engineering' },
  { name: 'Environmental Science' },
  { name: 'Environmental Studies' },
  { name: 'ERP Systems' },
  { name: 'European Law' },
  { name: 'Experimentation' },
  { name: 'Facilitation' },
  { name: 'Finance' },
  { name: 'Fine Arts' },
  { name: 'Flash' },
  { name: 'Food Science' },
  { name: 'Foreign Languages' },
  { name: 'Foreign Service' },
  { name: 'Forensic Psychology' },
  { name: 'Forensic Science' },
  { name: 'Forestry' },
  { name: 'Front-end Development' },
  { name: 'GAAP/FASB Knowledge' },
  { name: 'Geospatial Science' },
  { name: 'Geriatric Care' },
  { name: 'Google Analytics' },
  { name: 'Google Search' },
  { name: 'Governance and Organizational Sciences' },
  { name: 'Government Contracts' },
  { name: 'Graphic Design' },
  { name: 'Health Administration' },
  { name: 'Health Care Management' },
  { name: 'Health Informatics' },
  { name: 'Health Information Management' },
  { name: 'Health Science' },
  { name: 'Healthcare Administration' },
  { name: 'Heavy Machinery Operation' },
  { name: 'History' },
  { name: 'Hootsuite' },
  { name: 'Hospitality Management' },
  { name: 'HTML' },
  { name: 'Human Resource Development' },
  { name: 'Human Resources Management' },
  { name: 'Humanities' },
  { name: 'Hypertext' },
  { name: 'Industrial and Labor Relations' },
  { name: 'Industrial Engineering' },
  { name: 'Industrial Maintenance Technology' },
  { name: 'Information Assurance' },
  { name: 'Information Management' },
  { name: 'Information Security' },
  { name: 'Information Systems' },
  { name: 'Information Technology' },
  { name: 'Integrated Science' },
  { name: 'Interactive and Graphic Art' },
  { name: 'Interior Architecture and Design' },
  { name: 'International Affairs' },
  { name: 'International Business' },
  { name: 'International Economics' },
  { name: 'International Public Policy' },
  { name: 'International Relations' },
  { name: 'International Studies' },
  { name: 'Internetworking Technology' },
  { name: 'iOS App Development' },
  { name: 'Islamic Studies' },
  { name: 'Java Development' },
  { name: 'Journalism' },
  { name: 'Juridical Science' },
  { name: 'Jurisprudence' },
  { name: 'Landscape Architecture' },
  { name: 'Landscaping' },
  { name: 'Law' },
  { name: 'Leadership' },
  { name: 'Legal Management' },
  { name: 'Legal Office Administration' },
  { name: 'Legal Writing' },
  { name: 'Lesson Planning' },
  { name: 'Letters' },
  { name: 'Liberal Arts' },
  { name: 'Liberal Studies' },
  { name: 'Library and Information Science' },
  { name: 'Library Science' },
  { name: 'Linux' },
  { name: 'Mac, Linux and Unix Systems' },
  { name: 'Management' },
  { name: 'Manufacturing Engineering' },
  { name: 'Marketing' },
  { name: 'Marketing Campaign Management' },
  { name: 'Mass Communication and Journalism' },
  { name: 'Mathematics' },
  { name: 'Mechanical Engineering' },
  { name: 'Mediation' },
  { name: 'Medical Coding' },
  { name: 'Medical Science' },
  { name: 'Medical Technology' },
  { name: 'Medicine' },
  { name: 'Mentoring' },
  { name: 'Metallurgical Engineering' },
  { name: 'Meteorology' },
  { name: 'Microbiology' },
  { name: 'Microsoft Office Suite' },
  { name: 'Middleware and Integration Software' },
  { name: 'Middleware Technologies' },
  { name: 'Military Art and Science' },
  { name: 'Mind Mapping' },
  { name: 'Mining Engineering' },
  { name: 'Ministry' },
  { name: 'Mobile & Web Development' },
  { name: 'Modern Languages' },
  { name: 'Molecular Biology' },
  { name: 'Motivation' },
  { name: 'Museum Studies' },
  { name: 'Music' },
  { name: 'Music Composition' },
  { name: 'Musical Arts' },
  { name: 'MySQL' },
  { name: 'Naturopathic Medicine' },
  { name: 'Negotiation' },
  { name: 'Neonatal Care' },
  { name: 'Network and Communications Management' },
  { name: 'Network and Information Security' },
  { name: 'Network Structure & Security' },
  { name: 'Networking' },
  { name: 'Networking Communication' },
  { name: 'Neuroscience' },
  { name: 'Nursing' },
  { name: 'Nutrition Science' },
  { name: 'Occupational Therapy' },
  { name: 'Optimization' },
  { name: 'Optometry' },
  { name: 'Organization' },
  { name: 'Organizational Psychology' },
  { name: 'Osteopathic Medicine' },
  { name: 'Paid Online Traffic' },
  { name: 'Perl/Python/Ruby' },
  { name: 'Petroleum Engineering' },
  { name: 'Pharmacology' },
  { name: 'Pharmacy' },
  { name: 'Philosophy' },
  { name: 'Phlebotomy' },
  { name: 'Photography' },
  { name: 'Physical Therapy' },
  { name: 'Physician Assistant' },
  { name: 'Physics' },
  { name: 'Physiology' },
  { name: 'Pivot Tables' },
  { name: 'Planning' },
  { name: 'Planning / Event Planning' },
  { name: 'Plant Science' },
  { name: 'Podiatry' },
  { name: 'Political Science' },
  { name: 'Politics' },
  { name: 'Prenatal Care' },
  { name: 'Print Design & Typography' },
  { name: 'Project Management' },
  { name: 'Project Management Software' },
  { name: 'Project Performance Metrics' },
  { name: 'Providing Feedback' },
  { name: 'Psychology' },
  { name: 'Public Administration' },
  { name: 'Public Affairs' },
  { name: 'Public Diplomacy' },
  { name: 'Public Health' },
  { name: 'Public Management' },
  { name: 'Public Policy' },
  { name: 'Public Relations' },
  { name: 'Public Safety' },
  { name: 'Public Service' },
  { name: 'Public Speaking' },
  { name: 'Quality Assurance' },
  { name: 'Quantitative Finance' },
  { name: 'Quantity Surveying Engineering' },
  { name: 'Rabbinic Studies' },
  { name: 'Radio Oncology' },
  { name: 'Radiologic Technology' },
  { name: 'Real Estate Development' },
  { name: 'Real-Time Interactive Simulation' },
  { name: 'Religious Education' },
  { name: 'Research' },
  { name: 'Resource Management' },
  { name: 'Respiratory Therapy' },
  { name: 'Risk Management' },
  { name: 'Schedule Management' },
  { name: 'Scheduling' },
  { name: 'Search Engine Marketing (SEM)' },
  { name: 'Search Engine Optimization (SEO)' },
  { name: 'Security Engineering' },
  { name: 'Shell Scripting Languages' },
  { name: 'Sign Language' },
  { name: 'Social Media' },
  { name: 'Social Media Analytics' },
  { name: 'Social Science' },
  { name: 'Social Work' },
  { name: 'Software Development' },
  { name: 'Software Engineering' },
  { name: 'Software QA and User Testing' },
  { name: 'Software Revision Control Systems' },
  { name: 'Sports Management' },
  { name: 'Spreadsheets' },
  { name: 'Statistical Analysis' },
  { name: 'Statistical Analysis and Data Mining' },
  { name: 'Statistics' },
  { name: 'Storage & Data Management' },
  { name: 'Storage Systems and Management' },
  { name: 'Storytelling' },
  { name: 'Strategic Communication Management' },
  { name: 'Strategic Studies' },
  { name: 'Streamlining Processes' },
  { name: 'Supply Chain Management' },
  { name: 'Surgery' },
  { name: 'Surgery Assistance' },
  { name: 'Systems Analysis' },
  { name: 'Systems Engineering' },
  { name: 'Taxation' },
  { name: 'Teaching' },
  { name: 'Teamwork' },
  { name: 'Technical Reporting' },
  { name: 'Technical Writing' },
  { name: 'Technology' },
  { name: 'Telecommunications Technology' },
  { name: 'Television Production' },
  { name: 'Theology' },
  { name: 'Traction Management' },
  { name: 'Troubleshooting' },
  { name: 'Typing' },
  { name: 'Urban Planning' },
  { name: 'User Experience (UX) Design' },
  { name: 'User Interface (UI) Design' },
  { name: 'User Interface Design' },
  { name: 'UX/UI Design' },
  { name: 'Verbal Communication' },
  { name: 'Versatility' },
  { name: 'Veterinary Medicine' },
  { name: 'Veterinary Science' },
  { name: 'Veterinary Technology' },
  { name: 'Video Content Development' },
  { name: 'Virtual & Host-based Firewalls' },
  { name: 'Virtualization' },
  { name: 'Visual Communications' },
  { name: 'Vulnerability Analysis' },
  { name: 'Web Architecture' },
  { name: 'Web Architecture and Development Framework' },
  { name: 'Web Design' },
  { name: 'Web Development' },
  { name: 'Website Design' },
  { name: 'Wiki Creation' },
  { name: 'Wildlife Management' },
  { name: 'Word Processing' },
  { name: 'Wound Monitoring' },
  { name: 'Writing' },
  { name: 'Written Communication' },
];
